name: Security vulnerabilities check
on: push

jobs:
  snyk-software-composition-analysis-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code on the runner
        uses: actions/checkout@v4
      - name: Software Composition Analysis - Snyk dependency scan
        uses: snyk/actions/node@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

  # sonarqube-sast-code-quality-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out latest code on the runner
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Static App Security Testing - SonarQube code quality analysis
  #       uses: SonarSource/sonarqube-scan-action@v2
  #       env:
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       continue-on-error: true

  owasp-zap-dast-vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code on the runner
        uses: actions/checkout@v4
      - name: Dynamic App Security Testing - OWASP ZAP vulnerability scan
        uses: zaproxy/action-baseline@latest
        with:
          target: "http://localhost:4000"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
        continue-on-error: true
